JasonLG1979/gnome-shell-extensions-mediaplayer

README.md

README: link to the new DeaDBeeF plugin

---

po/LINGUAS
po/zh_CN.po

Update Chinese translation files.

---

src/panel.js

Fixes: Jumping of indicator icon if no status text is given and playback starts / stops

Show third indicator only if necessary

---

po/pt_BR.po

Brazilian portuguese translations - 100%

---

src/widget.js

The Nuvola Player's MPRIS interface provides following non-standard
vendor-prefixed rating API:
* the Player.NuvolaCanRate Boolean property, which is true when rating
is possible
* the Player.NuvolaSetRating(Double rating) method to set rating with
the double value having the same meaning as xesam:userRating in
Metadata property.
Upstream Issue: tiliado/nuvolaplayer#204

Add support for Nuvola Player's MPRIS rating API

---

src/player.js

Currently the sort order in _getPlaylists is hardcoded to "Alphabetical".
This fixes that by checking the Orderings prop and using "Alphabetical" if "Alphabetical" is in the provided Orderings or if no Orderings are provided. Otherwise it uses the first sort order in the Orderings array if one is provided but "Alphabetical" is not in it.

Don't hardcode the sort order of the playlists.

---

src/panel.js

And also not setting the size to 22 so it should just fill the panel button box and not distort.

Fix the icon not showing up in the panel it set to do so in the setting.

---

src/extension.js
src/manager.js
src/org.gnome.shell.extensions.mediaplayer.gschema.xml.in
src/panel.js
src/player.js
src/prefs.js
src/settings.js
src/stylesheet.css
src/ui.js
src/widget.js

As dicussed in https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/issues/298
Ratings in particular could use testing. I moved ratings out to it's own widget. Just need to make sure that I didn't break anything.

Many UI changes and improvements.

---

src/settings.js
src/ui.js

small clean up

---

src/extension.js

This will keep the default app in the extension up to date.

Watch for changes of the default apps

---

src/extension.js

To get the users .config dir instead of hardcoding it.

Use GLib.get_user_config_dir

---

src/manager.js

Now the default player is always 1st. Additional players are added from the top down.

Fix default player placement in the menu

---

src/panel.js
src/ui.js

Fixes https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/issues/313

Revert cover image validity check

---

src/extension.js
src/player.js
src/ui.js

Instead of playing cat and mouse to hide the default mpris applet

Monkey Patch _shouldShow

---

src/dbus.js
src/lib.js
src/manager.js
src/metadata.json.in
src/org.gnome.shell.extensions.mediaplayer.gschema.xml.in
src/panel.js
src/player.js
src/prefs.js
src/settings.js
src/stylesheet.css
src/ui.js
src/widget.js

And a bunch of other good stuff:
1. Asynchronous cover art handling with error checking.
2. Fixed the ratings box.
3. Fixed UI issues.
4. Main player menus behave more like a normal menu item.
5. Use the players symbolic icon in the menu if available. Use the active players symbolic icon in the panel if available.
6. The Indicator Appearance setting change is now instantaneous.
7. The run default setting now instantaneously shows or hides the indicator button in the panel(it only hides it if there isn't an active player) and the indicator button no longer takes up space in the panel if run default is not enabled.
8. The panel button only takes up as much space as absolutely necessary when shown. i.e. no extra space because of the hidden player status icon or text.

Added support for the MPRIS TrackList interface

---

Makefile.am

Fixes: #324

---

src/widget.js

1. Fixed a couple minor errors.
2. Added a getItem convenience method.
3. Reject the whole tracklist or playlists arrays if they don't contain unique object paths.

Misc fixes and refactoring

---

po/pt_BR.po

pt_BR - New translations

---

src/extension.js
src/manager.js
src/org.gnome.shell.extensions.mediaplayer.gschema.xml.in
src/panel.js
src/prefs.js
src/settings.js
src/ui.js

It's not very useful as a user can open a media player from the dash with just as many or less clicks this also simplifies the extension from a code standpoint.

Remove Default Player

---

src/org.gnome.shell.extensions.mediaplayer.gschema.xml.in
src/prefs.js
src/settings.js
src/ui.js

This adds 2 user settings.
Start with the cover zoomed and Raise the player when the cover is clicked.

Add more options

---

src/ui.js

Sometimes the song text failed to show this should fix that.

start zoomed prefs fixup

---

src/panel.js

Auto menu resize improvement

---

src/panel.js

I guess we have to hardcode the padding, 80px seems reasonable (40px othe either side).

more auto scaling fixes

---

src/player.js

1. Mainloop.timeout_add_seconds is more efficient than Mainloop.timeout_add since calls can be grouped to save CPU cycles.
2. Only delay the status update of PlayBackStatus for players that send a "Stopped" signal at song changes on "Stopped" not every status update.
3. In this.populate doing basically "potentially falsy or true" is pointless. It will always end up being true. It's the equivalent of foo = false || true, foo will always be true.

some logic tweaks

---

src/manager.js
src/player.js

Give players a very generous 1 sec to populate their interfaces before actually initializing/adding them. Seriously though folks ALL PROPERTIES should be ready before you take ownership of an interface name. If you don't know what a particular property really is at interface creation then use a dummy default value and then send a prop change signal when you do. TAKING OWNERSHIP OF AN EMPTY INTERFACE IS NOT OK. If you're doing that, you're doing it wrong and your implementation is broken, plain and simple. Missing boolean properties are partially ridiculous and inexcusable...

Fun with Mainloop timeouts

---

src/stylesheet.css
src/widget.js

Added extra padding to larger sizes, fixed initial padding and reordered code to always go from small to large.

Small tweaks to the last PR #404

---

src/manager.js
src/panel.js
src/player.js
src/settings.js
src/ui.js
src/util.js
src/widget.js

The following commits in this pull-request fix some of the JS warnings that are mentioned in #424.

Minor fixes to fix some JS warnings on gnome-shell 3.26

---

src/extension.js
src/org.gnome.shell.extensions.mediaplayer.gschema.xml
src/prefs.js
src/settings.js

This pull-request implements the left-indicator-position-feature as request in #423.
@JasonLG1979 
You're welcome ;-)

Support left indicator position

---

src/extension.js
src/stylesheet.css

Misaligned fix
