src/ui.js
If the player does not support a pause function hide the pause button during regular playback.
=> Show pause button only if the player supports it

src/player.js
If there is an error asking the mpris player for a position the position slider is hidden. If a later call provides a valid position enable the slider again if it was hidden before. Fixes #218.
=> Fix hidden position slider

src/player.js, src/ui.js
If media has no cover file and the genre contains the string "radio", use the "radio" icon instead of the "media-optical-cd-audio" icon.
=> Add support for an internet radio icon

src/player.js, src/ui.js
When `canPause` property is false, pause button is hidden. However, there wasn't any code to show it again when `canPause` property becomes true. In addition, `PropertiesChanged` signal for this property was ignored.
*Thanks for your work on this extension.*
=> Fix missing pause button

src/player.js
Reset wantedSeekValue after a regular seek to avoid wrong track position (fix for #239)
=> Fix track position

README.md, src/metadata.json.in
Now that GNOME Shell has its own media player control using MPRIS
(in the calendar/messages menu), this extension is less useful than
it was in previous versions, but it is still convenient to have a way
to place media player status directly on the top bar.
Signed-off-by: Simon McVittie <smcv@debian.org>
=> Add support for GNOME Shell 3.20

po/POTFILES.in
Caught by "make check".
Signed-off-by: Simon McVittie <smcv@debian.org>
=> Mark the GSettings schema for translation

src/ui.js
This fixes the issue where these fields remain unchanged from the previous file even when they are unavailable in the current file.
=> Clear artist, album, and title when they become unavailable

src/extension.js
Causes 'manager is null' js error
=> Do not disable already disabled extension

src/dbus.js
According to MPRIS2 specification the return type of the method
"GetPlaylists" should be "a(oss)".
See: https://specifications.freedesktop.org/mpris-spec/latest/Playlists_Interface.html#Method:GetPlaylists
=> Fix MediaServer2PlaylistsIFace

src/player.js
- Delay the initial call to get playlists because some
palyers (e.g. Rhythmbox) do not provide data if the interface gets
available
- Show playlists again if they where hidden because of an error
=> Make playlist interface more robust

src/metadata.json.in
In spirit of pull request #251, I suggest declaring compatibility with the newest shell version. In my tests, it works just as fine after the upgrade. This would also fix #277.
=> Add support for GNOME Shell 3.22

src/player.js
Timeouts will repeat if the function they call doesn't return false. There's no need for _startTimer to call it's self over and over again to reset the timeout when you can call a function that returns this.trackTime += 1 (Non false) in the timeout thus making it repeat until it's removed with _stopTimer.
=> Simplify the timer

src/player.js
Currently when a player updates it's ActivePlaylist prop the UI doesn't reflect that. Also if PlaylistCount changes the UI also needs to reload the playlists to reflect the change. This fixes both of those issues.
=> Update ActivePlaylist and PlaylistCount

src/lib.js
The regex was lacking the global flag and only replaced the 1st instance of the entity which resulted in fields not being displayed if there is more than one instance in the field. This fixes that by using GLib.markup_escape_text to escape all html entities.
=> Escape all html entities

src/player.js
trackId's are used thoughout the interfaces to refer to specific tracks and the docs are clear that a trackId must be present in the metadata and must be unique to a track.(even so far as if a track is repeated it should be given a new trackId)
xesam:url on the otherhand is not guaranteed to exist in the metadata and may not change on repeat especially if it is a real url pointing to the actual location of the media file.
This fixes the issue by also checking to see if the trackId has changed on a metadata refresh.
=> Add a trackId change as a trigger to tell the song has changed.

src/player.js
If the CanSeek prop changes the extension should call this._getPosition to decide if it wants to show the position slider or not. A player may want to change this prop mid song if for example it's playing a http stream and it's buffering or hasn't finished it's initial buffering yet.
=> Listen for the CanSeek prop change and respond accordingly.

src/ui.js
Also gaurds against crashing if there is not a default audio player set.
Fixes  https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/issues/267
=> Fixes the extension crashing because it can't resolve the .desktop file correctly.

src/player.js
Similar to the built-in MPRIS client in gnome-shell 3.20, rather than showing empty strings when these fields are unavailable, display "Unknown title", "Unknown album", and "Unknown artist" instead.
=> Add placeholders for title, album, and artist

src/ui.js, src/widget.js
Makes the control buttons and ratings boxes raise the player so that a player can be raised when it is not playing. This also sets hover for the volume and position sliders to false for visual continuity. Fixes https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/issues/220
=> Improve raise behaviour

src/stylesheet.css, src/ui.js, src/widget.js
GNOME uses symbolic icons just about every where especially in the actual shell.
"media-optical-cd-audio-symbolic" for most players and "application-rss+xml-symbolic" for "Radios" ("radio-symbolic" is just a circle in many themes i.e. for a radio button and "radio" doesn't even exist in the default GNOME icon theme?).
GNOME Shell 3.20 + users also get the nice "media-message-cover-icon fallback" style class borrowed from the default mpris controls for the default no cover icons to make them look more like an album cover.
In addition I did a little bit of code clean up.
=> Symbolic icons for the cover if the player doesn't provide a cover.

src/player.js, src/ui.js, src/widget.js
CanSeek now sets if the position slider is reactive not visible. If the player gives us a valid trackLength and position and the user wishes the position slider shown show it.
=> uncouple canSeek and position slider visibility

src/ui.js, src/widget.js
GNOME Shell menus are REALLY REALLY bad at figuring out when to/not add scrollbars and when not to overflow the screen. This just disables open and close animations all around for menus which seems to be source of the confusion.
=> More tweaking of the menus open and close

src/lib.js
There's no point in guarding parseMetadata.
=> fix no property text exception

src/widget.js
Feature #341 
MPRIS/D-BUS standard doesn't support setting ratings, so call out to the command-line, the same as for other apps
=> Add support for QuodLibet rating

src/manager.js, src/widget.js
GNOME Shell 3.24's js engine is more strict than previous versions and spams the logs with warnings.
=> Still More fixups for GNOME 3.24

src/settings.js, src/ui.js
Spotify's MPRIS implementation is broken:
https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/MPRIS-Implementation-is-severely-broken-in-the-Linux-client/td-p/1661880
This disables all but the most basic functionality for Spotify as Spotify is incapable of doing much else beyond the minimum correctly.
And also makes it easier to do the same to other poorly implemented players.
=> Handle Spotify's broken MPRIS implementation

src/extension.js, src/panel.js, src/stylesheet.css, src/ui.js
Dynamically change the PanelIndicator and Aggregate Menu width based on the large cover size and the Aggregate Menu. The menu size is defined as the natural width of the Aggregate Menu or the large cover size + a small amount of padding, whichever is larger. The Aggregate Menu may grow in width depending upon theme and cover size to accommodate the cover but will return to it's default width when no active player is present and/or the extension is disabled.
=> Dynamic menu width

src/widget.js
The js engine in GNOME 3.24 apparently really hates undefined. Even though the code works just fine and it's well within js code convention. They apparently think or want js to be python???
=> silence more useless GNOME 3.24 warnings

src/stylesheet.css
Apparently em's don't scale when going to HiDPI in GNOME Shell. So what little styling we do has to be in pixels...
=> Em's Don't Scale?

src/ui.js, src/widget.js
So that the main area appears more like one single widget when clicked.
=> Disable setting the active style_pseudo_class for some widgets

src/dbus.js
CanGoNext and CanGoPrevious were missing for some reason?
=> Add missing MPRIS props

src/lib.js, src/org.gnome.shell.extensions.mediaplayer.gschema.xml.in, src/panel.js, src/player.js, src/ui.js
Users can now put the name of the player in the panel if they want.
For example {playerName}: {trackArtist} - {trackTitle}.
=> add-player-name-to-trackbox-template

src/org.gnome.shell.extensions.mediaplayer.gschema.xml, src/player.js, src/prefs.js, src/settings.js, src/ui.js, src/widget.js
Currently on high DPI screens, the buttons to control playback are very small and somewhat hard to target.
This pull requests implements three different selectable sizes (apart from the existing one) to accommodate more screen resolutions.
=> Option to change the size of the playback button icons

src/prefs.js
This pull-request refactors some tiny parts in prefs.js. In short, it introduces the following changes:
* NotebookPage: add the public method getTitleLabel
* NotebookPage: make the variable title private by using the prefix _
* Notebook: override the public method Gtk.Notebook.append_page to avoid boilerplate code
=> prefs.js: refactor class Notebook and NotebookPage

build
This pull-request fixes two small issues with the build script:
* to find out the path to the shell (sh), we should use the handy program env.
in short, this will make of use of the user's $PATH variable.
* the build script uses the keyword `select`. however, select is not available
in sh, at least on my debian system :-). thus, we should use bash in the
shebang line. bash supports `select`.
=> build: fix shebang line

src/org.gnome.shell.extensions.mediaplayer.gschema.xml, src/panel.js, src/prefs.js, src/settings.js
This pull-request adds support to hide the player state icon (i.e., secondary indicator icon) as described in this comment here :-)
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/issues/403#issuecomment-331173064
=> Add support to hide the player state icon

src/mpi-symbolic.svg
Hi dev,
I made some minor adjustments to the icon.
For him to follow the Gnome guidelines, get more visible in 16 and 22px panels and align with
the baseline of the Gnome 3.26 indicator icons.
Result:
=> Tweak a icon to better appearence in 16 and 22px

src/metadata.json
Updated to include gnome-shell 3.28 to the supported versions.
=> Add gnome-shell 3.28 to metadata.json

src/metadata.json
Tested on Arch with gnome-shell 3.30 after the update that came yesterday.
=> Add gnome-shell 3.30 to metadata.json

src/stylesheet.css
Tweaks the existing fix for bug #448 to:
* Stop the first star and "previous" button losing their margins when siblings don't
* Fudge a spacer to give perfect centre alignment
=> Bug 448 alignment tweak

src/manager.js, src/metadata.json, src/panel.js, src/player.js, src/prefs.js, src/ui.js, src/widget.js
GNOME Shell 3.32 removed Lang.class() and we should be using ES6 classes instead. See https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/361
This change is mostly automated by https://github.com/DreaminginCodeZH/gnome-shell-es6-class-codemod . I've verified this locally on my GNOME Shell 3.32.
Also updated the `shell-version` in `metadata.json` because I've no idea if this will work on 3.30, or even older releases. If someone was able to verify it works, we can add it back.
This change fixes #476.
=> Port to GNOME Shell 3.32.
